## Numpy
- 한가지 자료형만 가능(모두 동일한 원소형으로 처리 속도 빠름)

`reshape`: 1차원 변경 함수
`reshape(4,5)` : 5개씩 4개로 묶음  / `reshape(2,2,5)` : 5개씩 2줄로 묶여져있는, 2개

In [13]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a, end='\n\n')

arr1 = np.arange(20)
print(arr1, end='\n\n')

arr2 = arr1.reshape(4,5)
print(arr2, end='\n\n')

arr3 = arr1.reshape(2,2,5)
print(arr3, end='\n\n')


[ 1  2  3  4  5  6  7  8  9 10]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

